mysql_root_password: 123@mudar
mysql_databases:
  - name: notes
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: notesapp
    host: "%"
    password: 123@mudar
    priv: "notes.*:ALL"